name: Publish

permissions: read-all

on:
  workflow_dispatch:
  push:
    tags:
      - '*v*'

jobs:
  npm-publish:
    name: Publish npm packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build packages
        run: npm run build
      - name: Set npm registry
        run: npm config set registry 'https://registry.npmjs.org/'
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_RELEASE}}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' $NODE_AUTH_TOKEN
          npm publish -w packages/puppeteer-core
          npm publish -w packages/puppeteer
      - name: Deprecate old Puppeteer versions
        if: ${{ startsWith(github.ref_name, 'puppeteer-v') }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_PUPPETEER}}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' $NODE_AUTH_TOKEN
          version_range=$(node tools/get_deprecated_version_range.js)
          npm deprecate puppeteer@"$version_range" "$version_range is no longer supported" || true
